### ISSUE TITLE
Question: Is it possible to derive an OIDC token from ADC which resolve to a user account?

### ISSUE THREAD

**Issue by joshuarli** [salrashid123/google_id_token#3]
Hello @salrashid123, thank you for writing https://medium.com/google-cloud/authenticating-using-google-openid-connect-tokens-e7675051213b, I found it to be very illuminating for understanding google auth.

I'm not sure if this is the right place to ask a question, but here goes.

The background is I'm writing a python client with google-auth to send an authenticated https request to trigger a GCF. Following your writing, I successfully got everything working with service accounts. The GCF is locked down to the service account like this:

```
gcloud --project PROJECT_NAME \
  functions add-iam-policy-binding FUNCTION_NAME \
  --member='serviceAccount:foobar@PROJECT_NAME.iam.gserviceaccount.com' \
  --role=roles/cloudfunctions.invoker
```

However, **is it possible to derive an acceptable token from application default credentials which resolve to a user account (`gcloud auth application-default login`), not a service account?**

My understanding is that GCF will only accept OIDC tokens, which can only be derived from service account credentials. User accounts are OAuth2 _access_ tokens which do not work.

For example, curling my GCF with 

```
-H "Authorization: Bearer $(gcloud auth application-default print-access-token)"
```

Fails with 401 Unauthorized. As opposed to `gcloud auth print-identity-token` which works because I believe it generates an OIDC token (that corresponds to the default compute engine service account? not sure here)

Thanks for your time.

---

Side note:

I see that `~/.config/gcloud/application_default_credentials.json` doesn't have things like the private key present in SA credential jsons...

https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.service_account.html#google.oauth2.service_account.IDTokenCredentials

> This profile differs from normal OAuth 2.0 profile because no user consent step is required. The use of the private key allows this profile to assert identity directly.

Brielfy skimming the code, the private key would be used in creating the necessary `google.auth.credentials.Signing`.

**Comment by salrashid123** [comment]
its a bit confusing but to give some context

* `gcloud auth application-default print-access-token`
   This prints out an oauth2 `access_token`

* `gcloud auth print-identity-token` 
  This prints out a google `id_token` but uses a user's own credential file for `gcloud` _cli_.  The type of flow that seeded this credential has a set `audience` value set to the `client_id` for gcloud cli (`32555940559.apps.googleusercontent.com`).

* `gcloud auth application-default print-access-token`
  This prints out the oauth2 access token associated with ADC (which actually uses a different `client_id` than gcloud cli)

---
The python library sdk you mentioned uses ADC; it does not use gcloud cli as the credential source (it just so happens that adc's credentail file is under ~/.config/gcloud...

Now,the only reason why `gcloud auth print-identity-token` works with GCF and Cloud Run is because those two  specifically have a whitelist that allows gcloud cli's client_id.  (i.,e its a bit of a cheat).


So, if you want to use python sdk (google-auth) library to invoke GCF, you need to use a service account flow since there isn't a way to derive an id_token for an audience that matches GCF's endpoint.  Also, the credentials embedded inside gcloud cli is not accessible from google-auth-python

**Comment by joshuarli** [comment]
Yup, it was also my understanding that various types of tokens generated by gcloud are mainly to only be used for testing, not real production stuff. Especially with the `gcloud auth print-identity-token` OIDC token.

Thank you for replying so quickly. Again, your medium post was immensely helpful to me, as well as all the example code you provided - it's a bit hard to figure out the correct APIs to use.

**Comment by joshuarli** [comment]
So, to recap:

> you need to use a service account flow since there isn't a way to derive an id_token for an audience that matches GCF's endpoint

This answers my question and confirms my understanding that GCF will only accept OIDC tokens, which can only be derived from service account credentials.
